spring:
  application:
    name: FlutterToDo
  datasource:
    url: jdbc:postgresql://${DB_IP}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: true
    change-log: db/changelog/changelog-master.yaml
    url: jdbc:postgresql://${DB_IP}:5432/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    liquibase-schema: public
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}
  jwtRefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS}
  redis:
    host: localhost
    port: 6379
